### ISSUE TITLE
Add code to customize the HTML and BODY tags?

### ISSUE THREAD

**Issue by jeremy-farrance** [chrismlusk/accuraty-templates#109]
Based on a convo from April (Slack), we might consider adding this code to includes/_registers.ascx or at least including it on the page commented out for as-needed future use and reference?

[Fine Tuning Your HTML Output](https://www.accuraty.com/web-design-champaign-urbana-savoy-il-news/dnn-fine-tuning-your-html-output)

**Comment by chrismlusk** [comment]
None of my requests (from the blog post) are that important, and so this seems to be unnecessary. Or at least outside the scope of this project.
