### ISSUE TITLE
Add "visible=false" attribute to containers?

### ISSUE THREAD

**Issue by chrismlusk** [chrismlusk/accuraty-templates#12]
Somehow, the `visible` attribute of DNN containers got lost during development. Should we restore that? Explanation from the docs:

> (Optional) You can add the attribute `visible="false"` to the pane to prevent it from being displayed if no module is assigned to it.

See [docs](https://www.dnnsoftware.com/docs/designers/creating-themes/create-container.html) for reference.

**Comment by chrismlusk** [comment]
@Accuraty, are you familiar with this attribute? I'm a little confused because I haven't been including it in any panes, but DNN adds the `.DNNEmptyPane` class when no module is assigned to it. So I'm just not sure what adding this to the templates would do. Any special knowledge you want to share?

**Comment by Accuraty** [comment]
I got nothin' on that one. Only thing to really do is see what others are doing. Might be a good idea to see if nvQuickTheme or Chris Hammond's HammerFlex (if updated recently) are still emitting either or both or other. But since those are the only obvious "docs" at this point, I would add the visible="false" (to the same element as the runat=server and test to see if it is doing what we expect?

**Comment by chrismlusk** [comment]
Yeah, we should restore this. DNN adds the `.DNNEmptyPane` class when you are logged in as an admin, but when you are not logged in and the pane has this attribute, DNN will prevent the code from being rendered, like the docs say.

**Comment by chrismlusk** [comment]
Somewhat related to this issue, here's how we can prevent the HTML that wraps an empty pane from rendering:

```asp
<%-- Don't render any HTML unless the pane has content. --%>
  <% if (ContentPane.Visible == true) { %>
    <section class="section">
      <div class="container">
        <div class="row">
          <div
            id="ContentPane"
            data-name="ContentPane"
            class="col-12"
            visible="false"
            runat="server"
          ></div>
        </div>
      </div>
    </section>
  <% } %>
```

Since modules and containers are typically focused just on their content, the layout templates have the grid structure — which leads to panes being wrapped like you see above. This extra markup is one of the reasons I've long avoided building a `Main.ascx` with multiple panes (content, left, right, full, etc.). Not every page needs each of those panes, and the empty markup usually inherited some styling that would screw with the layout.

But if we start using this kind of conditional, we could probably reduce the number of layout templates we use and also prevent unnecessary code from being sent to the browser. Win-win?

I need @Accuraty to weigh in, though. Any issues that you see?
