### ISSUE TITLE
Documentation Request: Outline how to compile SCSS

### ISSUE THREAD

**Issue by Accuraty** [chrismlusk/accuraty-templates#13]
Add a "plain English" description of where the SASS/SCSS files are and what processed are done to them, and where the destination (output) folder(s)/files end up.
 
Please also include a brief summary about how the above is happening 'out of the box' and where those settings are.
 
This is needed so that people using other editors and methods of SASS compiling (and linting and whatnot) can easily get up and running quickly.

**Comment by chrismlusk** [comment]
Added basic instructions to the project [`README.md`](https://github.com/chrismlusk/accuraty-templates#4-install-packages), a Skin overview to [`Skins/CLIENT_CODE/README.md`](https://github.com/chrismlusk/accuraty-templates/tree/master/Portals/_default/Skins/CLIENT_CODE#architecture), and Sass info to the [`/src/scss/README.md`](https://github.com/chrismlusk/accuraty-templates/tree/master/Portals/_default/Skins/CLIENT_CODE/src/scss).

I also started adding pages to the [Wiki](https://github.com/chrismlusk/accuraty-templates/wiki/FAQs). More work is needed. And we should probably have a discussion about how to intelligently organize all of this documentation between the README files and the Wiki.

**Comment by Accuraty** [comment]
Agreed. There are a lot of things "you just know" from experience or because you built [Frankenstein]. I wish there was a best practice way to structure the help/reminders. Things like how-to (steps) are very different from overview/reminder stuff like, "[Cliff Notes] on the correct way|places to set the client colors and typography." You'd think the Internetz woulda figured this out by now. ;)
