### ISSUE TITLE
Add "dotenv" to use environment variables?

### ISSUE THREAD

**Issue by chrismlusk** [chrismlusk/accuraty-templates#18]
Right now we have a variety of methods for configuring the project: reading npm variables from `package.json`, certain settings for Gulp in its `config/` directory, etc.

Should we consider adding [Dotenv](https://github.com/motdotla/dotenv) and moving these configurations into environment variables?

**Comment by Accuraty** [comment]
This is a worthwhile improvement IMHO. It kills me that pure JSON files have no option for comments. I've seen this pattern implemented in PHP too.

**Comment by chrismlusk** [comment]
Agreed. I'll do a little more research into this and start a feature branch.

**Comment by chrismlusk** [comment]
Closed by #44.
