### ISSUE TITLE
Add instructions for setting up new repo in Accuraty account

### ISSUE THREAD

**Issue by chrismlusk** [chrismlusk/accuraty-templates#21]
For ASL's benefit, add docs about setting up a new repo and the specific config we use.

**Comment by Accuraty** [comment]
Initial notes from recent attempt at 'working it thru'
- manually upload Containers/ABBV
- manually upload (selectively) Skins/ABBV/* (includes, controls, menus, public, src, and the *.ascx files in the root)
-- above two could be automatted on first build?
- edit the obvious "__REPLACEMENTS__" in includes/_footer.ascx and _logo.ascx
- uncommented the debug include at the bottom of _footer.ascx
- added my QueryString Params enhancement to __debug.ascx (please consider adding to the parent project)
- my normal cleanups to DNN's web.config (see diff or changelog, we eventually need a way to get some of these done automagically)
--- switch to better MSSQL connection
--- normal login persistence to 2 hours, but 4 days with Remember Me checked
--- passwords 14, 1, unque
--- verified assemblyIdentity has v10 bindingRedirect correct (thanks 2sxc!)
- added to Skin; src/scss/_base/_content2sxc.scss and wiring in Skin.scss

All of the above done on branch 'post-deploy-setup-config-standards' and committed to the Accuraty/ATSP repository here
https://github.com/Accuraty/PDEG/commit/9cb5e62fe040b628224e0fd14a01dcefaea63007

**Comment by Accuraty** [comment]
Here is an additional bit that I would like in there - or somewhere linked and easy to find. Probably needs some improvement by you.
 
### How to add and use various brand fonts correctly.

**Font API links**

1. An externally loaded font like TypeKit, Google Fonts, etc. 
a, in the `Skins/*/partials/_preheader.ascx` add them to DNN's CRM

Sample showing what you get from Adobe commented out:
<%-- 1. <link rel="stylesheet" href="https://use.typekit.net/qst6xaj.css"> --%>
<dnn:DnnCssInclude
  FilePath="https://use.typekit.net/qst6xaj.css"
  Priority="1"
  runat="server"
/>

2. Get the font defined in `Skins/*/src/scss/_abstracts/_variables.scss`, note there are two Typography sections... if just adding a one-off font for a specific use, add something like this with the other `$asl--` variables

`$asl--font-family-sans-serif-fancy: azo-sans-uber, sans-serif;`

Then something like this in the second Typography section

`$font-family-sans-serif-fancy:  $asl--font-family-sans-serif-fancy;`

3. Then in `Skins/*/src/scss/_base/_type.scss` you could have CSS like this

`h4 {
  &.fancy-heading {
    font-family: $font-family-sans-serif-fancy;
    font-weight: 400;
    font-style: normal;
  }
}`

**Using Font Files like TTF, etc.**
 
The following example uses the free [Dolce Vita TTF font](https://www.dafont.com/dolce-vita.font)... note that in a perfect world you should not be lazy and toss in all the variations if you only need and plan to use just one.

1. Simply put the actual files in `Skins/*/src/fonts`

![image](https://user-images.githubusercontent.com/653301/56083630-34718d00-5ded-11e9-80fd-3eacc06a1b98.png)

2 and 3. follow the same instructions as above for _variables and _type

**Comment by chrismlusk** [comment]
The scope of this issue was addressed in #57
