### ISSUE TITLE
Should "fixed" header be the default?

### ISSUE THREAD

**Issue by chrismlusk** [chrismlusk/accuraty-templates#22]
Right now the header defaults to use the `.fixed-to-top` utility class to make the header fixed by default. When it was just me using this project, I sort of was fine having it there and then removing it. However, most of our projects don't use the fixed header.

We should remove this.

**Comment by chrismlusk** [comment]
@Accuraty, unless you object, I'm planning on making this change today.

**Comment by Accuraty** [comment]
Any chance you already have enough of a pattern so the "Manage" nav/menu could also become a default? Keep in mind, that DNN 9+ we no longer name it "Manage" - from now on it is the "SITE" menu - and it will almost always exist on all our DNN projects will have a least  a few of these semi-standard pages:
### SITE
> Manage Users
> Manage Articles and Events
> Manage Publications
> Help (How-To, Reminders):
>> Filenames
>> Images
>> 5 Easy SEO Tips
