### ISSUE TITLE
Incorrect Commit, needs cleanup by you (CML)

### ISSUE THREAD

**Issue by Accuraty** [chrismlusk/accuraty-templates#23]
Got confused about naming and committed a new branch to 'Accuraty' instead of 'origin' and it was actually chrismlusk/accuraty-templates. Sorry, burned hand teaches best, learning from my mistakes (I hope).
https://github.com/chrismlusk/accuraty-templates/commits/post-deploy-setup-config-standards

**Comment by chrismlusk** [comment]
It looks like all you did was push up a new branch (not commit anything to the `master` branch, so I'll just delete that branch.
