### ISSUE TITLE
Add favicon generator to build process

### ISSUE THREAD

**Issue by chrismlusk** [chrismlusk/accuraty-templates#39]
Let's automate modern favicon creation. 

Take a look at this: https://github.com/RealFaviconGenerator/gulp-real-favicon

**Comment by Accuraty** [comment]
Ha, wow, didn't even notice someone had done that. Does it make sense to incorporate this in to 'accuraty-templates' or should we do a separate mini-project or something? It doesn't feel like it belongs in here to me, but not sure. Maybe we could just document the steps to add it when we are doing finalization?

**Comment by chrismlusk** [comment]
I'm not sure yet. Generally speaking, some form of "modern" favicon output should be included in this project — because all website projects need good favicons. More research/experimentation is needed before adding it to the `accuraty-templates` codebase, but I think ENVRX will be a good test case (since that project is close to finalization).
