### ISSUE TITLE
Rename "content" styles to "rich text"?

### ISSUE THREAD

**Issue by chrismlusk** [chrismlusk/accuraty-templates#59]
Originally, I decided to create `_content.scss` so we could have a wrapper class to handle WYSIWYG generated content where only HTML tags were available. Since every module in DNN ends up with a `.DnnModule` class, I extended that into `.DnnModule__content`. With the increased use of DNN 2sxc and the clashing terminology, however, I think this should change to help reduce confusion.

My proposal is to move the current "content" styles under a class called `.rich-text`. That way, these content styles don't rely on DNN modules, 2sxc views, or anything else — we just apply the class where needed. For example:

```html
<div class="DnnModule__content rich-text"></div>
```

```html
<div class="co-container-inner rich-text"></div>
```

```html
<div class="custom-component-in-the-skin rich-text"></div>
```

Thoughts, @Accuraty?

**Comment by Accuraty** [comment]
Is this something you’ve seen done elsewhere? An established pattern?

**Comment by chrismlusk** [comment]
We do this at One Design, and it's really effective.

But overall, this move is in alignment with the philosophy of having flexible, modular CSS since a `.rich-text` class is more reusable. This is the same approach Bootstrap takes.
