### ISSUE TITLE
DDRMenu: Razor and XSLT templates

### ISSUE THREAD

**Issue by Accuraty** [chrismlusk/accuraty-templates#7]
I'm submitting a feature request about theming/skinning and the DDRMenu. Currently there is only one plain text (Simple) token template for the DDRMenu. 

We should add Razor and XSLT templates. The output should be as identical as possible. This would help the 'themer' easily have a starting point for their preferred template technology.
 
Jeremy could or should probably do this if we can work through a pull request.

**Comment by chrismlusk** [comment]
Closing this issue since the `NavPrimary` and `NavSecondary` menus now have Razor. Future DDR template requests can be submitted as their own issues.
