### ISSUE TITLE
Implement FIRST, LAST, and ONLY on all menus

### ISSUE THREAD

**Issue by Accuraty** [chrismlusk/accuraty-templates#77]
Even if use-cases are sometimes rare (at least for .only), we definitely need to implement class output for .first, .last, and .only in all our menus.

@chrismlusk, do you know what the standard class names should be? do we need "first" or "nav-first" or ??
 
Other than the class name to add, this should be as simple as...

```
        if (node.First) {
          itemClasses.Add("first");
        }
        if (node.Last) {
          itemClasses.Add("last");
        }
        if (node.Only) {
          itemClasses.Add("only");
        }
```

**Comment by chrismlusk** [comment]
If the use case is rare, why do you think it should be included by default?

You had me remove code previously because it might negatively affect compile performance. Isn't this a similar situation (since those are lines of code that have to be evaluated on each instance of the loop)?

In all projects, the devs have to modify this code. It's just a matter of do you go in looking to remove code that doesn't fit your use case or add code when you need it? 

It comes down to which philosophy should guide this template:
1. a starting point with common needs addressed
2. or a collection of all possible use cases

**Comment by chrismlusk** [comment]
I'm also be interested to know what the value or desired outcome is. For referencing elements, these are essentially the same:

```css
.nav-item.first { ... }
.nav-item:first-child { ... }

.nav-item.last { ... }
.nav-item:last-child { ... }


```

**Comment by chrismlusk** [comment]
Also, I don't think `node.Only` is correct. I just tried it and it broke the menu. I also don't see it listed [here](https://www.dnnsoftware.com/wiki/ddrmenu-razor-templates). (Of course, these docs are poorly maintained.)

**Comment by Accuraty** [comment]
I was not aware that CSS had a way to solve this without any 'helper indications'. My mindset is still in the old days. Also, the performance hit here is extremely tiny, especially considering this type of stuff is small and cached and minified and combined, etc. 
 
My real ongoing goal is to continue to prevent staff/other devs/etc from spending time figuring things out (that they do not know). Today, Josh wasted a significant amount of time on BCSP because he added a Page and the menu item, with the 'Open in New Window' DNN feature wasn't working. Because the NavPrimary code was older and didn't have the node.Target implemented. If it had been there (even in-place as self-documentation but commented out), I wouldn't have lost an hour+ labor time that could have gone towards other useful stuff. This happens a lot.

**Comment by chrismlusk** [comment]
Old days?! The `:first-child` selector was first introduced in the CSS2 spec in 1998. I guess you _are_ old!! 😉

I agree with the goal: We should equip everyone with the resources/knowledge so they can be as efficient as possible. Don't forget that there is a README in every directory, although the [one in the "menus" folder](https://github.com/chrismlusk/accuraty-templates/blob/master/Portals/_default/Skins/CLIENT_CODE/menus/README.md) definitely needs work. You make a good point about self-documentation, and adding comments about DDRMenu with links to the API docs is an easy win.
