### ISSUE TITLE
Enhance and refactor `SidebarMenu.cshtml` 

### ISSUE THREAD

**Issue by jeremy-farrance** [chrismlusk/accuraty-templates#80]
I believe it is worthwhile to add (rewrite or refactor too) this
https://github.com/Accuraty/PDEG/blob/2499a6e9b67f101963e91fe66cb9cfc1ebb9eca4/DesktopModules/RazorModules/RazorHost/Scripts/_SidebarMenu.cshtml#L75
 
In to the same file here. It could use a little TLC?
 
You can see it [working here on PDEG](http://pdeg.accuraty.ws/destinations/al-hattendorf-center/preschool-early-childhood/overview), expand the Programs submenu.

**Comment by chrismlusk** [comment]
With the adoption of 2sxc, this RazorHost script isn't needed. It would be nice to build something for 2sxc to have a standard sidebar menu, but that's a future issue.
